### ISSUE TITLE
Packaged block disapearing when breaking it and cannot unpack with right-click [MC 1.16.2 + Forge-33.0.60 + PackingTape-1.16.2-0.9.7.jar]

### ISSUE THREAD

**Issue by ghost** [gigaherz/PackingTape#26]
Hello,

I am unable to break a Packaged block on my server or unpack it with right click. When breaking it, it disappear and right-clicking does nothing.

Server is running on MC 1.16.2 + Forge-33.0.60 + PackingTape-1.16.2-0.9.7.jar

Here is the error in the log file:

`[12Nov2020 11:18:28.403] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.NullPointerException: null
	at gigaherz.packingtape.tape.PackagedBlock.func_225533_a_(PackagedBlock.java:137) ~[?:0.9.7]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227031_a_(AbstractBlock.java:634) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:338) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:889) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:729) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:156) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:712) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:706) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:691) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]`

Thank you!

**Comment by gigaherz** [comment]
I'll take a look as soon as I can.

**Comment by gigaherz** [comment]
Uhm, do you have a mod list for your server? Something must be causing the data in the packaged block TileEntity to be wiped, and this should never ever happen.
I'll add a workaround to avoid crashing and allow breaking the block, but the real damage has already been done: the contents of the package are no longer there.

**Comment by ghost** [comment]
No problem! Nothing important was in the chest since I was just testing it! 

Here is the mod list of the server :

- AdFinders-1.16.2-5.0.2.0-build.0012.jar
- collective-1.16.2-1.39.jar
- constructionwand-1.16.2-1.2.jar
- CookingForBlockheads_1.16.2-9.1.0.jar
- EnderMail-1.16.2-1.1.4.jar
- essentials-1.16.2-2.9.0.jar
- extlights-3.1.jar
- FarmingForBlockheads_1.16.2-7.1.0.jar
- ForgeEndertech-1.16.2-7.0.2.0-build.0012.jar
- ftb-backups-2.1.1.6.jar
- ftb-ultimine-1.1.0.10.jar
- globalxp-1.16.2-v1.4.13.jar
- gravestone-1.16.1-1.0.2.jar
- ironchest-1.16.2-11.1.5.jar
- jei-1.16.2-7.1.3.20.jar
- minecolonies-0.13.239-ALPHA-universal.jar
- Morpheus-1.16.2-4.2.58.jar
- MouseTweaks-2.13-mc1.16.2.jar
- nhacampfire_1.16.2-2.4.jar
- PackingTape-1.16.2-0.9.7.jar
- pamhc2foodcore-1.16.2-1.0.0.jar
- Patchouli-1.16-42.jar
- reap-1.16.2-1.0.1.jar
- refinedstorage-1.9.3.jar
- simplemagnets-1.0.5-mc1.16.2.jar
- SimpleStorageNetwork-1.16.2-1.0.1.jar
- simplylight-1.16.2-1.0.2.jar
- sit-1.16.2-v1.3.jar
- StorageDrawers-1.16.2-8.1.0.jar
- strawgolem-1.16.2-1.9-beta-2.jar
- structurize-0.13.66-ALPHA.jar
- TinyMobFarm-1.16.2-1.1.0.jar
- torcherino-12.0.0%2B1.16.2.jar
- TravelersBackpack-1.16.2-5.1.1.jar
- u_team_core-1.16.2-3.1.4.172.jar
- useful_backpacks-1.16.2-1.11.3.76.jar
- Waystones_1.16.2-7.2.0.jar

Thanks a lot!
